#pragma once

#define ZXING_VERSION_MAJOR 3
#define ZXING_VERSION_MINOR 1
#define ZXING_VERSION_PATCH 0
#define ZXING_VERSION_STR "3.1.0"

#define ZXING_READERS 1

#define ZXING_ENABLE_1D 0
#define ZXING_ENABLE_AZTEC 0
#define ZXING_ENABLE_DATAMATRIX 0
#define ZXING_ENABLE_MAXICODE 0
#define ZXING_ENABLE_PDF417 0
#define ZXING_ENABLE_QRCODE 1
